options:
  docker: true

pipelines:
  branches: 
    development:
      - step:
          deployment: development-build
          name: Build
          image: python:3.6
          caches:
            - docker
          script:
            - export BITBUCKET_REPO_NAME="`sed 's|worcket/|development\/|' <<< $BITBUCKET_REPO_FULL_NAME`"
            - pip install awscli
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names $BITBUCKET_REPO_NAME > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name $BITBUCKET_REPO_NAME
            - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - docker build --pull -t ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER .
            - docker tag ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME
            - docker push ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER
    qa:
      - step:
          deployment: qa-build
          name: Build
          image: python:3.6
          caches:
            - docker
          script:
            - export BITBUCKET_REPO_NAME="`sed 's|worcket/|qa\/|' <<< $BITBUCKET_REPO_FULL_NAME`"
            - pip install awscli
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names $BITBUCKET_REPO_NAME > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name $BITBUCKET_REPO_NAME
            - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - docker build --pull -t ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER .
            - docker tag ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME
            - docker push ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER
    master:
      - step:
          deployment: production-build
          name: Build
          image: python:3.6
          caches:
            - docker
          script:
            - export BITBUCKET_REPO_NAME="`sed 's|worcket/|production\/|' <<< $BITBUCKET_REPO_FULL_NAME`"
            - pip install awscli
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names $BITBUCKET_REPO_NAME > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name $BITBUCKET_REPO_NAME
            - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - docker build --pull -t ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER .
            - docker tag ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME
            - docker push ${AWS_REGISTRY_URL}/$BITBUCKET_REPO_NAME:$BITBUCKET_BUILD_NUMBER