apiVersion: v1
kind: Secret
metadata:
  name: candidates-listenner
  # namespace: infra
type: Opaque
data:
  # echo -n mongodb+srv://USER:PASSW@qa-tihwj.mongodb.net/wrckdb | base64
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9hd3NsYW1iZGE6dHV6aGliLXBvS3ppcy12ZXZjaTVAcWEtdGlod2oubW9uZ29kYi5uZXQvd3Jja2Ri
  # echo -n redis://redis-bus:6379 | base64
  REDIS_URI: cmVkaXM6Ly9yZWRpcy1idXM6NjM3OQ== 
  # echo -n candidates | base64
  REDIS_PUSH_CHANNEL: Y2FuZGlkYXRlcw==
  MONGODB_COLLECTION: Y2FuZGlkYXRlcw==
  #echo -n testRank,ageRange,experienceRange,educationLevel,languages,professions,skills,fieldsOfStudy | base64
  MONGODB_WATCH_PROPERTIES: dGVzdFJhbmssYWdlUmFuZ2UsZXhwZXJpZW5jZVJhbmdlLGVkdWNhdGlvbkxldmVsLGxhbmd1YWdlcyxwcm9mZXNzaW9ucyxza2lsbHMsZmllbGRzT2ZTdHVkeQ==
  # echo -n 3000 | base64
  HEALTHCHECK_PORT: MzAwMA==
  # echo -n verbose | base64
  DEBUG: dmVyYm9zZQ==
  