options:
  docker: true

pipelines:
  branches:
    release:
      - step:
          deployment: qa-build
          name: Build
          image: python:3.6
          caches:
            - docker
          script:
            - pip install --no-cache-dir awscli docker-compose
            - docker-compose -v
            - sed -i 's/UPDATE_TAG/$BITBUCKET_BUILD_NUMBER/g' docker-compose-release.yml
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names qa/listenner > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name qa/listenner
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names qa/puller > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name qa/puller
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names qa/ranker > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name qa/ranker
            - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - npm run clean
            - npm run build
            - docker-compose -f docker-compose.yml -f docker-compose-release.yml build
            - docker-compose -f docker-compose.yml -f docker-compose-release.yml push
    master:
      - step:
          deployment: production-build
          name: Build
          image: python:3.6
          caches:
            - docker
          script:
            - pip install --no-cache-dir awscli docker-compose
            - docker-compose -v
            - sed -i 's/UPDATE_TAG/$BITBUCKET_BUILD_NUMBER/g' docker-compose-production.yml
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names qa/listenner > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name qa/listenner
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names qa/puller > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name qa/puller
            - aws ecr describe-repositories --region ${AWS_DEFAULT_REGION} --repository-names qa/ranker > /dev/null 2>&1 || aws --region ${AWS_DEFAULT_REGION} ecr create-repository --repository-name qa/ranker
            - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
            - npm run clean
            - npm run build
            - docker-compose -f docker-compose.yml -f docker-compose-production.yml build
            - docker-compose -f docker-compose.yml -f docker-compose-production.yml push
