#docker-compose.yml
version: '3.3'    
services:
  listenner:
    image: k3d-rank-registry.localhost:63333/listenner:latest
    build:
      context: ./
      dockerfile: ./packages/listenner/Dockerfile
  puller:
    image: k3d-rank-registry.localhost:63333/puller:latest
    build:
      context: ./
      dockerfile: ./packages/puller/Dockerfile
  ranker:
    image: k3d-rank-registry.localhost:63333/ranker:latest
    build:
      context: ./
      dockerfile: ./packages/ranker/Dockerfile
