#docker-compose.yml
version: '3.3'    
services:
  listenner:
    image: 333623647139.dkr.ecr.eu-west-1.amazonaws.com/qa/listenner:latest
    build:
      context: ./
      dockerfile: ./packages/listenner/Dockerfile
  puller:
    image: 333623647139.dkr.ecr.eu-west-1.amazonaws.com/qa/puller:latest
    build:
      context: ./
      dockerfile: ./packages/puller/Dockerfile
  ranker:
    image: 333623647139.dkr.ecr.eu-west-1.amazonaws.com/qa/ranker:latest
    build:
      context: ./
      dockerfile: ./packages/ranker/Dockerfile
