#docker-compose.yml
version: '3.3'    
services:
  listenner:
    image: 333623647139.dkr.ecr.eu-west-1.amazonaws.com/qa/listenner:UPDATE_TAG
    build:
      context: ./
      dockerfile: ./packages/listenner/Dockerfile
  puller:
    image: 333623647139.dkr.ecr.eu-west-1.amazonaws.com/qa/puller:UPDATE_TAG
    build:
      context: ./
      dockerfile: ./packages/puller/Dockerfile
  ranker:
    image: 333623647139.dkr.ecr.eu-west-1.amazonaws.com/qa/ranker:UPDATE_TAG
    build:
      context: ./
      dockerfile: ./packages/ranker/Dockerfile
