#docker-compose.yml
version: '3.3'    
services:
  listenner:
    image: 333623647139.dkr.ecr.us-east-1.amazonaws.com/production/listenner:UPDATE_TAG
    build:
      context: ./
      dockerfile: ./packages/listenner/Dockerfile
  puller:
    image: 333623647139.dkr.ecr.us-east-1.amazonaws.com/production/puller:UPDATE_TAG
    build:
      context: ./
      dockerfile: ./packages/puller/Dockerfile
  ranker:
    image: 333623647139.dkr.ecr.us-east-1.amazonaws.com/production/ranker:UPDATE_TAG
    build:
      context: ./
      dockerfile: ./packages/ranker/Dockerfile
