---
apiVersion: v1
kind: Service
metadata:
  name: candidates-puller
  labels:
    app: puller
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
      app: puller
  type: LoadBalancer
