apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: new-service
  namespace: [environment]
spec:
  backendType: vault
  vaultMountPoint: commons-[environment].k8s.local
  vaultRole: commons-[environment].k8s.local
  kvVersion: 2
  dataFrom:
    - [environment]/data/new-service
