---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidates-ranker
  # namespace: [environment]
  labels:
    app: ranker
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
    secret.reloader.stakater.com/reload: "ranker"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ranker
  template:
    metadata:
      labels:
        app: ranker
    spec:
      imagePullSecrets:
      - name: aws-registry
      containers:
      - name: candidates-ranker
        image: k3d-rank-registry:63333/ranker:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: candidates-ranker
        ports:
        - containerPort: 3002
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
