---
apiVersion: v1
kind: Service
metadata:
  name: candidates-ranker
  labels:
    app: puller
spec:
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
      app: puller
  type: LoadBalancer
