---
apiVersion: v1
kind: Service
metadata:
  name: ranker
  # namespace: [environment]
  labels:
    app: ranker
spec:
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
      app: ranker
  type: LoadBalancer
