---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listenner
  # namespace: [environment]
  labels:
    app: listenner
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
    secret.reloader.stakater.com/reload: "listenner"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: listenner
  template:
    metadata:
      labels:
        app: listenner
    spec:
      imagePullSecrets:
      - name: aws-registry
      containers:
      - name: listenner
        image: k3d-registry.localhost:5000/listenner:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: listenner
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
