---
apiVersion: v1
kind: Service
metadata:
  name: listenner
  # namespace: [environment]
  labels:
    app: listenner
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
      app: listenner
  type: LoadBalancer
