apiVersion: v1
kind: Secret
metadata:
  name: opportunities-listenner
  # namespace: infra
type: Opaque
data:
  # echo -n mongodb+srv://USER:PASSW@qa-tihwj.mongodb.net/wrckdb | base64
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9hd3NsYW1iZGE6dHV6aGliLXBvS3ppcy12ZXZjaTVAcWEtdGlod2oubW9uZ29kYi5uZXQvd3Jja2Ri
  # echo -n redis://redis-bus:6379 | base64
  REDIS_URI: cmVkaXM6Ly9yZWRpcy1idXM6NjM3OQ== 
  # echo -n opportunities | base64
  REDIS_PUSH_CHANNEL: b3Bwb3J0dW5pdGllcw==
  MONGODB_COLLECTION: b3Bwb3J0dW5pdGllcw==
  #echo -n testRank,ageRange,experienceRange,educationLevelsAdvanced,languages,professions,skillsReq,fieldsOfStudy | base64
  MONGODB_WATCH_PROPERTIES: dGVzdFJhbmssYWdlUmFuZ2UsZXhwZXJpZW5jZVJhbmdlLGVkdWNhdGlvbkxldmVsc0FkdmFuY2VkLGxhbmd1YWdlcyxwcm9mZXNzaW9ucyxza2lsbHNSZXEsZmllbGRzT2ZTdHVkeQ==
  # echo -n 3000 | base64
  HEALTHCHECK_PORT: MzAwMA==
  # echo -n verbose | base64
  DEBUG: dmVyYm9zZQ==
  