---
apiVersion: v1
kind: Service
metadata:
  name: opportunities-listenner
  labels:
    app: opportunities-listenner
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
      app: opportunities-listenner
  type: ClusterIP
