---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: [new-service]
  namespace: [environment]
  labels:
    app: [new-service]
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
    secret.reloader.stakater.com/reload: "[new-service]"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: [new-service]
  template:
    metadata:
      labels:
        app: [new-service]
    spec:
      imagePullSecrets:
      - name: aws-registry
      containers:
      - name: [new-service]
        image: 333623647139.dkr.ecr.[aws-region].amazonaws.com/[environment]/[new-service]:[build_number]
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: [new-service]
        ports:
        - containerPort: [new-service-PORT]
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
