---
apiVersion: v1
kind: Service
metadata:
  name: [new-service]
  namespace: [environment]
  labels:
    app: [new-service]
spec:
  ports:
    - port: [new-service-PORT]
      targetPort: [new-service-PORT]
      protocol: TCP
      name: http
  selector:
      app: [new-service]
  type: ClusterIP
