---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opportunities-puller
  # namespace: [environment]
  labels:
    app: opportunities-puller
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
    secret.reloader.stakater.com/reload: "opportunities-puller"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: opportunities-puller
  template:
    metadata:
      labels:
        app: opportunities-puller
    spec:
      imagePullSecrets:
      - name: aws-registry
      containers:
      - name: opportunities-puller
        image: k3d-rank-registry:63333/puller:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: opportunities-puller
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
